// const { type } = require("@generated/site-storage");

module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Welcome to SAAS',
      items: [
        {
  type: 'category',
  label: 'Welcome to DNIF',
  link: {
    type: 'doc',
    id: 'documents/Welcome-to-DNIF/welcome-to-dnif' // This is the main doc that opens when the dropdown is clicked
  },
  items: [
    {
      type: 'category',
      label: 'Quick Start Guide',
      items: [{ type: 'autogenerated', dirName: 'documents/Welcome-to-DNIF/Quick Start Guide' }]
    },
    {
      type: 'category',
      label: 'Installation',
      items: [{ type: 'autogenerated', dirName: 'documents/Welcome-to-DNIF/Installation' }]
    },
    {
      type: 'category',
      label: 'DNIF UI',
      items: [{ type: 'autogenerated', dirName: 'documents/Welcome-to-DNIF/DNIF UI' }]
    }
  ]
},

        {
          type: 'category',
          label: 'Connect, Extract and Enrich',
          items: [
            {
              type: 'category',
              label: 'Device Integration',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Device-Integration' }]
            },

        
            {
              type: 'category',
              label: 'Connectors',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Connectors' }]
            },
            {
              type: 'category',
              label: 'Data Ingestion',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Data-Ingestion' }]
            },
            {
              type: 'category',
              label: 'Data Extraction',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Data-Extraction' }]
            },
            {
              type: 'category',
              label: 'Enrichment',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Enrichment' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Hunting with Workbooks',
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Getting-Started' }]
            },
            {
              type: 'category',
              label: 'Visualization',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Visualization' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Dnif Query Language',
          items: [
            {
              type: 'category',
              label: 'Schema On Read',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Schema-on-Read' }]
            },
            {
              type: 'category',
              label: 'Query By Multiple Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query multiple streams' }]
            },
            {
              type: 'category',
              label: 'Query By Source Name',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query by source name' }]
            },
            {
              type: 'category',
              label: 'Pipes',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/PIPES' }]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Overview' }]
            },
            {
              type: 'category',
              label: 'Functions',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Functions' }]
            },
            {
              type: 'category',
              label: 'DQL Legacy',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Legacy' }]
            },
            {
              type: 'category',
              label: 'DQL Cheatsheet',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Cheatsheet' }]
            },
            {
              type: 'category',
              label: 'Basic syntax',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Basic syntax' }]
            },
            {
              type: 'category',
              label: 'DQL Right from Start',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Right from Start' }]
            },
          ]
        },
       {
  type: 'category',
  label: 'Security Monitoring',
  items: [
    { type: 'autogenerated', dirName: 'documents/Security-Monitoring' },

    {
      type: 'category',
      label: 'Investigating Signals',
      items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Investigating Signals' }]
    },
    {
      type: 'category',
      label: 'Case Management',
      items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Case Management' }]
    },
    {
      type: 'category',
      label: 'Mitre Attack',
      items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/MITRE ATT&CK' }]
    },
  ]
},

        {
          type: 'category',
          label: 'User Management and Access Control',
          items: [
            {
              type: 'category',
              label: 'Users and Roles',
              items: [
                {
                  type: 'category',
                  label: 'DNIF Entities',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/DNIF-Entities' }]
                },
                {
                  type: 'category',
                  label: 'Manage Organization and users',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Organization and users' }]
                },
                {
                  type: 'category',
                  label: 'Manage Tenants and access',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Tenants and access' }]
                },
              ]
            },
            {
              type: 'category',
              label: 'Authentication',
              items: [
                {
                  type: 'category',
                  label: 'LDAP Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/LDAP Authentication' }]
                },
                {
                  type: 'category',
                  label: 'SAML Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/SAML Authentication' }]
                },
                {
                  type: 'category',
                  label: 'Two-Factor Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/Two - Factor Authentication' }]
                },
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Solution Design',
          items: [{ type: 'autogenerated', dirName: 'documents/Solution-Design' }]
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            {
              type: 'category',
              label: 'Collection Status',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Collection Status' }]
            },
            {
              type: 'category',
              label: 'Managing Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Managing Streams' }]
            },
            {
              type: 'category',
              label: 'Manage Dashboard',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Dashboard' }]
            },
            {
              type: 'category',
              label: 'Manage Reports',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Reports' }]
            },
            {
              type: 'category',
              label: 'Slow Queries',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Slow Queries' }]
            },
            {
              type: 'category',
              label: 'Manage Tokens',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Token' }]
            },
            {
              type: 'category',
              label: 'Event Stores',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Event Stores' }]
            },
            {
              type: 'category',
              label: 'Change Task Timeouts',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Change Task Timeouts' }]
            },
            {
              type: 'category',
              label: 'Machine Learning',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Machine Learning' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Platform Services',
          items: [
            {
              type: 'category',
              label: 'Supported Automation',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation' }]
            },
            {
              type: 'category',
              label: 'Supported Automation-SSH',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation-SSH' }]
            },
            {
              type: 'category',
              label: 'API',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/API' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Troubleshooting and Debugging',
          items: [{ type: 'autogenerated', dirName: 'documents/Troubleshooting-and-Debugging' }]
        },
       {
  type: 'category',
  label: 'DNIF AI',
  items: [
    {
      type: 'doc',
      id: 'documents/DNIF-AI/Getting-Started-with-DNIF-AI/getting-started-with-dnif-ai',
      label: 'Getting Started with DNIF AI'
    },
     
    {
     type: 'doc',
     id: 'documents/DNIF-AI/Extractor-Generator-Overview/extractor-generator-overview',
     label: 'Extractor Generator Overview'
    }
    
  ]
},
        {
          type: 'category',
          label: 'License Management and Billing',
          items: [
           {
      type: 'doc',
      id: 'documents/License-Management-and-Billing/Calculating-overage/calculating-overage-2',
      label: 'Calculating Overage',
    },
    {
      type: 'doc',
      id: 'documents/License-Management-and-Billing/Pricing-to-billing-how-it-works/pricing-to-billing-how-it-works-3',
      label: 'Pricing to billing, how it works',
    },
            {
              type: 'doc',
              id: 'documents/License-Management-and-Billing/Term-Based-Software-Subscription/term-based-software-subscription',
              label: 'Term Based Software Subscription ',
            },
          ]
        },
        {
  type: 'category',
  label: 'DNIF Legal and Security Compliance',
  items: [
    {
      type: 'doc',
      id: 'documents/DNIF-Legal-and-Security-Compliance/Data-Privacy-Policy/data-privacy-policy',
      label: 'Data Privacy Policy'
    },
     
    {
     type: 'doc',
     id: 'documents/DNIF-Legal-and-Security-Compliance/DNIF-End-user-License-Agreement/dnif-end-user-license-agreement',
     label: 'DNIF End user License Agreement '
    }
    
  ]
},
        {
          type: 'category',
          label: 'Policies',
          items: [{ type: 'autogenerated', dirName: 'documents/Policies' }]
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{ type: 'autogenerated', dirName: 'documents/Best-Practices' }]
        },
        {
          type: 'category',
          label: 'Release Notes',
          items: [{ type: 'autogenerated', dirName: 'documents/Release-Notes' }]
        }
      ] // <-- This closes the 'items' array for 'Documents'
    }
  ], // <-- This closes the 'sidebar' array
  sidebarForOnPrem: [
    // {
    //   type: 'category',
    //   label: 'Release Notes',
    //   items: [{ type: 'autogenerated', dirName: 'documents/Release-Notes' }]
    // },
    {
      type: 'category',
      label: 'Welcome to On-Prem',
      items: [
        {
  type: 'category',
  label: 'Welcome to DNIF',
  link: {
    type: 'doc',
    id: 'hyperscale/Welcome to DNIF/welcome-to-dnif' // This doc opens when the category label is clicked
  },
  items: [
    {
      type: 'category',
      label: 'Quick Start Guide',
      items: [
        { type: 'autogenerated', dirName: 'hyperscale/Welcome to DNIF/Quick Start Guide' }
      ]
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        { type: 'autogenerated', dirName: 'hyperscale/Welcome to DNIF/Installation' }
      ]
    },
    {
      type: 'category',
      label: 'DNIF UI',
      items: [
        { type: 'autogenerated', dirName: 'hyperscale/Welcome to DNIF/DNIF UI' }
      ]
    }
  ]
},


    {
          type: 'category',
          label: 'Connect, Extract and Enrich',
          items: [
            {
              type: 'category',
              label: 'Device Integration',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Device-Integration' }]
            },
            {
              type: 'category',
              label: 'Connectors',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Connectors' }]
            },
            {
              type: 'category',
              label: 'Data Ingestion',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Data-Ingestion' }]
            },
            {
              type: 'category',
              label: 'Data Extraction',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Data-Extraction' }]
            },
            {
              type: 'category',
              label: 'Enrichment',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Enrichment' }]
            }
          ]
        },
       {
          type: 'category',
          label: 'Hunting with Workbooks',
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Hunting-with-Workbooks/Getting-Started' }]
            },
            {
              type: 'category',
              label: 'Visualization',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Hunting-with-Workbooks/Visualization' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Dnif Query Language',
          items: [
            {
              type: 'category',
              label: 'Schema On Read',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Schema-on-Read' }]
            },
             {
              type: 'category',
              label: 'Query By Multiple Streams',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Query multiple streams' }]
            },
            {
              type: 'category',
              label: 'Query By Source Name',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Query by source name' }]
            },
            {
              type: 'category',
              label: 'Pipes',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/PIPES' }]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Overview' }]
            },
            {
              type: 'category',
              label: 'Functions',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Functions' }]
            },
            {
              type: 'category',
              label: 'DQL Legacy',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Legacy' }]
            },
            {
              type: 'category',
              label: 'DQL Cheatsheet',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Cheatsheet' }]
            },
            {
              type: 'category',
              label: 'Basic syntax',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Basic syntax' }]
            },
            {
              type: 'category',
              label: 'DQL Right from Start',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Right from Start' }]
            },
          ]
        },
       {
  type: 'category',
  label: 'Security Monitoring',
  items: [
    { type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring' },

    {
      type: 'category',
      label: 'Investigating Signals',
      items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/Investigating Signals' }]
    },
    {
      type: 'category',
      label: 'Case Management',
      items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/Case Management' }]
    },
    {
      type: 'category',
      label: 'Mitre Attack',
      items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/MITRE ATT&CK' }]
    },
  ]
},

        {
          type: 'category',
          label: 'User Management and Access Control',
          items: [
            {
              type: 'category',
              label: 'Users and Roles',
              items: [
                {
                  type: 'category',
                  label: 'DNIF Entities',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Users-and-Roles/DNIF-Entities' }]
                },
                {
                  type: 'category',
                  label: 'Manage Organization and users',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Users-and-Roles/Manage Organization and users' }]
                },
              ]
            },
            {
              type: 'category',
              label: 'Authentication',
              items: [
                {
                  type: 'category',
                  label: 'LDAP Authentication',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Authentication/LDAP Authentication' }]
                },

                {
                  type: 'category',
                  label: 'Two-Factor Authentication',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Authentication/Two - Factor Authentication' }]
                },
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            
            {
              type: 'category',
              label: 'Managing Streams',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Managing Streams' }]
            },
           
            {
              type: 'category',
              label: 'Slow Queries',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Slow Queries' }]
            },
            {
              type: 'category',
              label: 'Manage Tokens',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Manage Token' }]
            },
            {
              type: 'category',
              label: 'Event Stores',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Event Stores' }]
            },
            {
              type: 'category',
              label: 'Change Task Timeouts',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Change Task Timeouts' }]
            },
            {
              type: 'category',
              label: 'Machine Learning',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Machine Learning' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Platform Services',
          items: [
            {
              type: 'category',
              label: 'Supported Automation',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/Supported Automation' }]
            },
            {
              type: 'category',
              label: 'Supported Automation-SSH',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/Supported Automation-SSH' }]
            },
            {
              type: 'category',
              label: 'API',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/API' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Troubleshooting and Debugging',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Troubleshooting-and-Debugging' }]
        },
        {
          type: 'category',
          label: 'DNIF AI',
          items: [
            { type: 'doc', id: 'hyperscale/DNIF-AI/Getting-Started-with-DNIF-AI/getting-started-with-dnif-ai', label: 'Getting Started with DNIF AI' },
            
          ]
        },
      {
  type: 'category',
  label: 'License Management and Billing',
  items: [
    {
      type: 'doc',
      id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Calculating-overage/calculating-overage-2',
      label: 'Calculating Overage',
    },
    {
      type: 'doc',
      id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Pricing-to-billing-how-it-works/pricing-to-billing-how-it-works-3',
      label: 'Pricing to billing, how it works',
    },
    {
      type: 'doc',
      id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Term-Based-Software-Subscription/term-based-software-subscription',
      label: 'Term Based Software Subscription',
    },
  ]
},


         {
  type: 'category',
  label: 'DNIF Legal and Security Compliance',
  items: [
    {
      type: 'doc',
      id: 'hyperscale/DNIF-Legal-and-Security-Compliance/Data-Privacy-Policy/data-privacy-policy',
      label: 'Data Privacy Policy'
    },
     
    {
     type: 'doc',
     id: 'hyperscale/DNIF-Legal-and-Security-Compliance/DNIF-End-user-License-Agreement/dnif-end-user-license-agreement',
     label: 'DNIF End user License Agreement '
    }
    
  ]
},
        {
          type: 'category',
          label: 'Policies',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Policies' }]
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Best-Practices' }]
        },
      ]}
       

      
  

    
]}; // <-- This closes the module.exports object

