// const { type } = require("@generated/site-storage");

module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Documents',
      items: [
        // {
        //   type: 'category',
        //   label: 'Getting Started',
        //   items: [
        //     {
        //       type: 'category',
        //       label: 'Inroduction To DNIF',
        //       items: [{ type: 'autogenerated', dirName: 'documents/Getting-Started/Introduction-To-Dnif' }]
        //     },
        //     {
        //       type: 'category',
        //       label: 'Quick Start Guide',
        //       items: [{ type: 'autogenerated', dirName: 'documents/Getting-Started/Quick Start Guide' }]
        //     },
        //     {
        //       type: 'category',
        //       label: 'Pre-requisites Audit',
        //       items: [{ type: 'autogenerated', dirName: 'documents/Getting-Started/Pre-requisites Audit' }]
        //     },
        //     {
        //       type: 'category',
        //       label: 'Installation',
        //       items: [{ type: 'autogenerated', dirName: 'documents/Getting-Started/Installation' }]
        //     },
        //     {
        //       type: 'category',
        //       label: 'DNIF UI',
        //       items: [{ type: 'autogenerated', dirName: 'documents/Getting-Started/Dnif Ui' }]
        //     },
        //   ]
        // },
        {
          type: 'category',
          label: 'Connect, Extract and Enrich',
          items: [
            {
              type: 'category',
              label: 'Device Integration',
              items: [{ type: 'autogenerated', dirName: 'documents/Connect,Extract-and-Enrich/Device-Integration' }]
            },
            {
              type: 'category',
              label: 'Connectors',
              items: [{ type: 'autogenerated', dirName: 'documents/Connect,Extract-and-Enrich/Connectors' }]
            },
            {
              type: 'category',
              label: 'Data Extraction',
              items: [{ type: 'autogenerated', dirName: 'documents/Connect,Extract-and-Enrich/Data-Extraction' }]
            },
            {
              type: 'category',
              label: 'Enrichment',
              items: [{ type: 'autogenerated', dirName: 'documents/Connect,Extract-and-Enrich/Enrichment' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Hunting with Workbooks',
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Getting-Started' }]
            },
            {
              type: 'category',
              label: 'Visualization',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Visualization' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Dnif Query Language',
          items: [
            {
              type: 'category',
              label: 'Schema On Read',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Schema-on-Read' }]
            },
            {
              type: 'category',
              label: 'Query By Multiple Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query multiple streams' }]
            },
            {
              type: 'category',
              label: 'Query By Source Name',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query by source name' }]
            },
            {
              type: 'category',
              label: 'Pipes',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/PIPES' }]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Overview' }]
            },
            {
              type: 'category',
              label: 'Functions',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Functions' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Security Monitoring',
          items: [
            {
              type: 'category',
              label: 'Investigating Signals',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Investigating Signals' }]
            },
            {
              type: 'category',
              label: 'Case Management',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Case Management' }]
            },
            {
              type: 'category',
              label: 'Mitre Attack',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/c.MITRE ATT&CK' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'User Management and Access Control',
          items: [
            {
              type: 'category',
              label: 'Users and Roles',
              items: [
                {
                  type: 'category',
                  label: 'DNIF Entities',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/DNIF-Entities' }]
                },
                {
                  type: 'category',
                  label: 'Manage Organization and users',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Organization and users' }]
                },
                {
                  type: 'category',
                  label: 'Manage Tenants and access',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Tenants and access' }]
                },
              ]
            },
            {
              type: 'category',
              label: 'Authentication',
              items: [
                {
                  type: 'category',
                  label: 'LDAP Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/LDAP Authentication' }]
                },
                {
                  type: 'category',
                  label: 'SAML Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/SAML Authentication' }]
                },
                {
                  type: 'category',
                  label: 'Two-Factor Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/Two - Factor Authentication' }]
                },
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Solution Design',
          items: [{ type: 'autogenerated', dirName: 'documents/Solution-Design' }]
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            {
              type: 'category',
              label: 'Collection Status',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Collection Status' }]
            },
            {
              type: 'category',
              label: 'Managing Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Managing Streams' }]
            },
            {
              type: 'category',
              label: 'Manage Dashboard',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Dashboard' }]
            },
            {
              type: 'category',
              label: 'Slow Queries',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Slow Queries' }]
            },
            {
              type: 'category',
              label: 'Manage Tokens',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Token' }]
            },
            {
              type: 'category',
              label: 'Event Stores',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Event Stores' }]
            },
            {
              type: 'category',
              label: 'Change Task Timeouts',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Change Task Timeouts' }]
            },
            {
              type: 'category',
              label: 'Machine Learning',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Machine Learning' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Platform Services',
          items: [
            {
              type: 'category',
              label: 'Supported Automation',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation' }]
            },
            {
              type: 'category',
              label: 'Supported Automation-SSH',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation-SSH' }]
            },
            {
              type: 'category',
              label: 'API',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/API' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Troubleshooting and Debugging',
          items: [{ type: 'autogenerated', dirName: 'documents/Troubleshooting-and-Debugging' }]
        },
        {
          type: 'category',
          label: 'DNIF AI',
          items: [
            { type: 'doc', id: 'documents/DNIF-AI/Getting-Started-with-DNIF-AI/getting-started-with-dnif-ai', label: 'Getting Started with DNIF AI' },
            {
              type: 'category',
              label: 'Extractor Generator Overview',
              items: [{ type: 'autogenerated', dirName: 'documents/License-Management-and-Billing/License-Management-and-Billing/Term-Based-Software-Subscription' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'License Management and Billing',
          items: [
            {
              type: 'category',
              label: 'Term Based Software Subscription',
              items: [{ type: 'autogenerated', dirName: 'documents/License-Management-and-Billing/License-Management-and-Billing/Term-Based-Software-Subscription' }]
            },
            {
              type: 'category',
              label: 'Pricing to billing , how it works',
              items: [{ type: 'autogenerated', dirName: 'documents/License-Management-and-Billing/License-Management-and-Billing/Pricing to billing , how it works' }]
            },
            {
              type: 'category',
              label: 'Calculating Overage',
              items: [{ type: 'autogenerated', dirName: 'documents/License-Management-and-Billing/License-Management-and-Billing/Calculating  overage' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'DNIF Legal and Security Compliance',
          items: [{ type: 'autogenerated', dirName: 'documents/DNIF-Legal-and-Security-Compliance' }]
        },
        {
          type: 'category',
          label: 'Policies',
          items: [{ type: 'autogenerated', dirName: 'documents/Policies' }]
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{ type: 'autogenerated', dirName: 'documents/Best-Practices' }]
        },
        {
          type: 'category',
          label: 'Release Notes',
          items: [{ type: 'autogenerated', dirName: 'documents/Release-Notes' }]
        }
      ] // <-- This closes the 'items' array for 'Documents'
    }
  ], // <-- This closes the 'sidebar' array
  sidebarForOnPrem: [
    // {
    //   type: 'category',
    //   label: 'Release Notes',
    //   items: [{ type: 'autogenerated', dirName: 'documents/Release-Notes' }]
    // },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'hyperscale' }]
    }]
}; // <-- This closes the module.exports object




