// const { type } = require("@generated/site-storage");

module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Welcome to HYPERCLOUD',
      items: [
        {
          type: 'category',
          label: 'Welcome to DNIF',
          link: {
            type: 'doc',
            id: 'documents/Welcome-to-DNIF/welcome-to-dnif' // This is the main doc that opens when the dropdown is clicked
          },
          items: [
            {
              type: 'doc',
              id: 'documents/Welcome-to-DNIF/Quick Start Guide/quick-start-guide',
              label: 'Quick Start Guide',
            },
            {
              type: 'doc',
              id: 'documents/Welcome-to-DNIF/Installation/pico-installation',
              label: 'Installation',
            },
            {
              type: 'doc',
              id: 'documents/Welcome-to-DNIF/DNIF UI/dnif-ui-overview',
              label: 'DNIF UI',
            },
            {
              type: 'doc',
              id: 'documents/Welcome-to-DNIF/Before You Begin/before-you-begin',
              label: 'Before You Begin',
            },
            {
              type: 'doc',
              id: 'documents/Welcome-to-DNIF/Pre-Requisites Audit/pre-requisites-audit',
              label: 'Pre-requisites Audit',
            },

          ]
        },

        {
          type: 'category',
          label: 'Connect, Extract and Enrich',
          items: [
            {
              type: 'doc',
              id: 'documents/connect-extract-enrich/Intro_Connectors_extract_enrich',
              label: "Introduction to Connectors, Extractors, and Enrichment"
            },
            {
              type: 'category',
              label: 'Device Integration',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Device-Integration' }]
            },


            {
              type: 'category',
              label: 'Connectors',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Connectors' }]
            },
            {
              type: 'category',
              label: 'Data Ingestion',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Data-Ingestion' }]
            },
            {
              type: 'category',
              label: 'Data Extraction',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Data-Extraction' }]
            },
            {
              type: 'category',
              label: 'Enrichment',
              items: [{ type: 'autogenerated', dirName: 'documents/connect-extract-enrich/Enrichment' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Hunting with Workbooks',
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Getting-Started' }]
            },
            {
              type: 'category',
              label: 'Visualization',
              items: [{ type: 'autogenerated', dirName: 'documents/Hunting-with-Workbooks/Visualization' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'DNIF Query Language',
          items: [
             {
              type: 'doc',
              id: 'documents/Dnif-Query-Language/DQL_Intro',
              label: "Introduction to DQL"
            },
            {
              type: 'category',
              label: 'Schema On Read',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Schema-on-Read' }]
            },
            {
              type: 'category',
              label: 'Query By Multiple Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query multiple streams' }]
            },
            {
              type: 'category',
              label: 'Query By Source Name',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Query by source name' }]
            },
            {
              type: 'category',
              label: 'Pipes',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/PIPES' }]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Overview' }]
            },
            {
              type: 'category',
              label: 'Functions',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Functions' }]
            },
            {
              type: 'category',
              label: 'DQL Legacy',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Legacy' }]
            },
            {
              type: 'category',
              label: 'DQL Cheatsheet',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Cheatsheet' }]
            },
            {
              type: 'category',
              label: 'Basic syntax',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/Basic syntax' }]
            },
            {
              type: 'category',
              label: 'DQL Right from Start',
              items: [{ type: 'autogenerated', dirName: 'documents/Dnif-Query-Language/DQL Right from Start' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Security Monitoring',
          items: [
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/Security-monitoring',
              label: 'Security Monitoring',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/streamline-alert-analysis-with-signal-tagging',
              label: 'Streamline Alert Analysis with Signal Tagging',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/workbook-versioning-track-collaborate-and-restore-with-ease',
              label: 'Workbook Versioning: Track, Collaborate, and Restore with Ease',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/what-is-security-monitoring',
              label: 'What is Security Monitoring?',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/creating-signal-suppression-rules',
              label: 'Creating Signal Suppression Rules',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/why-eba',
              label: 'Why EBA?',
            },
            {
              type: 'doc',
              id: 'documents/Security-Monitoring/signal-suppression-rule',
              label: 'Signal Suppression Rule',
            },

            {
              type: 'category',
              label: 'Investigating Signals',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Investigating Signals' }]
            },
            {
              type: 'category',
              label: 'Case Management',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/Case Management' }]
            },
            {
              type: 'category',
              label: 'Mitre Attack',
              items: [{ type: 'autogenerated', dirName: 'documents/Security-Monitoring/MITRE ATT&CK' }]
            },
          ]
        },

        {
          type: 'category',
          label: 'User Management and Access Control',
          items: [
            {
              type: 'doc',
              id: 'documents/User-Management-and-Access-Control/User-Management-in-DNIF',
              label: 'User Management in DNIF',
            },

            {
              type: 'category',
              label: 'Users and Roles',
              items: [
                {
                  type: 'category',
                  label: 'DNIF Entities',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/DNIF-Entities' }]
                },
                {
                  type: 'category',
                  label: 'Manage Organization and users',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Organization and users' }]
                },
                {
                  type: 'category',
                  label: 'Manage Tenants and access',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Users-and-Roles/Manage Tenants and access' }]
                },
              ]
            },
            {
              type: 'category',
              label: 'Authentication',
              items: [
                {
                  type: 'category',
                  label: 'LDAP Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/LDAP Authentication' }]
                },
                {
                  type: 'category',
                  label: 'SAML Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/SAML Authentication' }]
                },
                {
                  type: 'category',
                  label: 'Two-Factor Authentication',
                  items: [{ type: 'autogenerated', dirName: 'documents/User-Management-and-Access-Control/Authentication/Two - Factor Authentication' }]
                },
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Solution Design',
          items: [{ type: 'autogenerated', dirName: 'documents/Solution-Design' }]
        },

         {
              type: 'doc',
              id: 'documents/Solution-Design/Solution-Design',
              label: 'Solution-Design',
            },
        {
          type: 'category',
          label: 'Operations',
          items: [
            {
              type: 'category',
              label: 'Collection Status',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Collection Status' }]
            },
            {
              type: 'category',
              label: 'Managing Streams',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Managing Streams' }]
            },
            {
              type: 'category',
              label: 'Manage Dashboard',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Dashboard' }]
            },
            {
              type: 'category',
              label: 'Manage Reports',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Reports' }]
            },
            {
              type: 'category',
              label: 'Slow Queries',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Slow Queries' }]
            },
            {
              type: 'category',
              label: 'Manage Tokens',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Manage Token' }]
            },
            {
              type: 'category',
              label: 'Event Stores',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Event Stores' }]
            },
            {
              type: 'category',
              label: 'Change Task Timeouts',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Change Task Timeouts' }]
            },
            {
              type: 'category',
              label: 'Machine Learning',
              items: [{ type: 'autogenerated', dirName: 'documents/Operations/Machine Learning' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Platform Services',
          items: [
            {
              type: 'doc',
              id: 'documents/Platform-Services/automation',
              label: 'Automation',
            },
            {
              type: 'category',
              label: 'Supported Automation',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation' }]
            },
            {
              type: 'category',
              label: 'Supported Automation-SSH',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/Supported Automation-SSH' }]
            },
            {
              type: 'category',
              label: 'API',
              items: [{ type: 'autogenerated', dirName: 'documents/Platform-Services/API' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Troubleshooting and Debugging',
          items: [{ type: 'autogenerated', dirName: 'documents/Troubleshooting-and-Debugging' }]
        },

        {
              type: 'doc',
              id: 'documents/Troubleshooting-and-Debugging/Troubleshooting-and-Debugging',
              label: 'Trobleshooting and Debugging',
        },
        {
          type: 'category',
          label: 'DNIF AI',
          items: [
            {
              type: 'doc',
              id: 'documents/DNIF-AI/Getting-Started-with-DNIF-AI/getting-started-with-dnif-ai',
              label: 'Getting Started with DNIF AI'
            },

            {
              type: 'doc',
              id: 'documents/DNIF-AI/Extractor-Generator-Overview/extractor-generator-overview',
              label: 'Extractor Generator Overview'
            }

          ]
        },
        {
          type: 'category',
          label: 'License Management and Billing',
          items: [
            {
              type: 'doc',
              id: 'documents/License-Management-and-Billing/Calculating-overage/calculating-overage-2',
              label: 'Calculating Overage',
            },
            {
              type: 'doc',
              id: 'documents/License-Management-and-Billing/Pricing-to-billing-how-it-works/pricing-to-billing-how-it-works-3',
              label: 'Pricing to billing, how it works',
            },
            {
              type: 'doc',
              id: 'documents/License-Management-and-Billing/Term-Based-Software-Subscription/term-based-software-subscription',
              label: 'Term Based Software Subscription ',
            },
          ]
        },
        {
          type: 'category',
          label: 'DNIF Legal and Security Compliance',
          items: [
            {
              type: 'doc',
              id: 'documents/DNIF-Legal-and-Security-Compliance/Data-Privacy-Policy/data-privacy-policy',
              label: 'Data Privacy Policy'
            },

            {
              type: 'doc',
              id: 'documents/DNIF-Legal-and-Security-Compliance/DNIF-End-user-License-Agreement/dnif-end-user-license-agreement',
              label: 'DNIF End user License Agreement '
            }

          ]
        },
        {
          type: 'category',
          label: 'Policies',
          items: [{ type: 'autogenerated', dirName: 'documents/Policies' }]
        },
        {
          type: 'category',
          label: 'PICO',
          items: [{ type: 'autogenerated', dirName: 'documents/PICO' }]
        },
        {
          type: 'category',
          label: 'Security Bulletins',
          items: [{ type: 'autogenerated', dirName: 'documents/Security-Bulletins' }]
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{ type: 'autogenerated', dirName: 'documents/Best-Practices' }]
        },

        {
          type: 'category',
          label: 'Release Notes',
          items: [
            //         {
            //   type: 'doc',
            //   id: 'documents/Security-Monitoring/streamline-alert-analysis-with-signal-tagging',
            //   label: 'May 21, 2025 – Content Update',
            // },
            {
              type: 'doc',
              id: 'documents/Release-Notes/april-17-2025-content-update',
              label: 'April 17, 2025- Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/march-25th-2025-content-update',
              label: 'March 25, 2025- Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/march-18th-2025-application-update',
              label: 'March 18, 2025 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/march-5th-2025-application-update',
              label: 'March 5, 2025 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/january-29-2025-content-update',
              label: 'January 29, 2025 - Content update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/january-27-2025-application-update',
              label: 'January 27, 2025 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-december-30-2024-content-update',
              label: 'December 30, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-basedecember-12-2024-content-update',
              label: 'December 12, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-december-3-2024-application-update',
              label: 'December 3, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-november-15-2024-content-update',
              label: 'November 15, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-october-26-2024-application-update',
              label: 'October 26, 2024- Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-october-23-2024-content-update',
              label: 'October 23, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/knowledge-base-october-16-2024-application-update',
              label: 'October 16, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/september-04-2024-application-update',
              label: 'September 04, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/september-04-2024-content-update',
              label: 'September 04, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/august-27-2024-application-update',
              label: 'August 27, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/july-30-2024-application-update',
              label: 'July 30, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/june-04-2024-application-update',
              label: 'June 04, 2024- Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/april-24-2024-application-update',
              label: 'April 24, 2024- Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/march-26-2024-application-update',
              label: 'March 26, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/february-19-2024-application-update',
              label: 'February 19, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/january-09-2024-content-update',
              label: 'January 09, 2024 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/january-09-2024-application-update',
              label: 'January 09, 2024 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/november-27-2023-content-update',
              label: 'November 27, 2023 - Content Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/november-27-2023-application-update',
              label: 'November 27, 2023 - Application Update',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/october-05-2023-application-update-release-notes-v9-3-3',
              label: 'October 05, 2023 - Application Update (Release Notes v9.3.3)',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/may-30-2023-application-update-release-notes-v9-3-2',
              label: 'May 30, 2023 - Application Update (Release Notes v9.3.2)',
            },
            {
              type: 'doc',
              id: 'documents/Release-Notes/november-29-2022-application-update-release-notes-v9-3-0',
              label: 'November 29, 2022 - Application Update (Release Notes v9.3.0)',
            },
          ]
        }
      ] // <-- This closes the 'items' array for 'Documents'
    }
  ], // <-- This closes the 'sidebar' array
  sidebarForOnPrem: [
    // {
    //   type: 'category',
    //   label: 'Release Notes',
    //   items: [{ type: 'autogenerated', dirName: 'documents/Release-Notes' }]
    // },
    {
      type: 'category',
      label: 'Welcome to HYPERSCALE',
      items: [
        {
          type: 'category',
          label: 'Welcome to DNIF',
          link: {
            type: 'doc',
            id: 'hyperscale/Welcome to DNIF/welcome-to-dnif' // This doc opens when the category label is clicked
          },
          items: [
            {
              type: 'doc',
              id: 'hyperscale/Welcome to DNIF/Quick Start Guide/quick-start-guide',
              label: 'Quick Start Guide',
            },
            {
              type: 'doc',
              id: 'hyperscale/Welcome to DNIF/Installation/pico-installation',
              label: 'Installation',
            },
            {
              type: 'doc',
              id: 'hyperscale/Welcome to DNIF/DNIF UI/dnif-ui-overview',
              label: 'DNIF UI',
            },
            {
              type: 'doc',
              id: 'hyperscale/Welcome to DNIF/Before You Begin/before-you-begin',
              label: 'Before You Begin',
            },
            {
              type: 'doc',
              id: 'hyperscale/Welcome to DNIF/Pre-Requisites Audit/pre-requisites-audit',
              label: 'Pre-requisites Audit',
            },
          ]
        },


        {
          type: 'category',
          label: 'Connect, Extract and Enrich',
          items: [
            {
              type: 'category',
              label: 'Device Integration',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Device-Integration' }]
            },
            {
              type: 'category',
              label: 'Connectors',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Connectors' }]
            },
            {
              type: 'category',
              label: 'Data Ingestion',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Data-Ingestion' }]
            },
            {
              type: 'category',
              label: 'Data Extraction',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Data-Extraction' }]
            },
            {
              type: 'category',
              label: 'Enrichment',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/connect-extract-enrich/Enrichment' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'Hunting with Workbooks',
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Hunting-with-Workbooks/Getting-Started' }]
            },
            {
              type: 'category',
              label: 'Visualization',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Hunting-with-Workbooks/Visualization' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'DNIF Query Language',
          items: [
            {
              type: 'category',
              label: 'Schema On Read',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Schema-on-Read' }]
            },
            {
              type: 'category',
              label: 'Query By Multiple Streams',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Query multiple streams' }]
            },
            {
              type: 'category',
              label: 'Query By Source Name',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Query by source name' }]
            },
            {
              type: 'category',
              label: 'Pipes',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/PIPES' }]
            },
            {
              type: 'category',
              label: 'Overview',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Overview' }]
            },
            {
              type: 'category',
              label: 'Functions',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Functions' }]
            },
            {
              type: 'category',
              label: 'DQL Legacy',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Legacy' }]
            },
            {
              type: 'category',
              label: 'DQL Cheatsheet',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Cheatsheet' }]
            },
            {
              type: 'category',
              label: 'Basic syntax',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/Basic syntax' }]
            },
            {
              type: 'category',
              label: 'DQL Right from Start',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Dnif-Query-Language/DQL Right from Start' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Security Monitoring',
          items: [
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/streamline-alert-analysis-with-signal-tagging',
              label: 'Streamline Alert Analysis with Signal Tagging',
            },
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/workbook-versioning-track-collaborate-and-restore-with-ease',
              label: 'Workbook Versioning: Track, Collaborate, and Restore with Ease',
            },
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/what-is-security-monitoring',
              label: 'What is Security Monitoring?',
            },
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/creating-signal-suppression-rules',
              label: 'Creating Signal Suppression Rules',
            },
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/why-eba',
              label: 'Why EBA?',
            },
            {
              type: 'doc',
              id: 'hyperscale/Security-Monitoring/signal-suppression-rule',
              label: 'Signal Suppression Rule',
            },


            {
              type: 'category',
              label: 'Investigating Signals',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/Investigating Signals' }]
            },
            {
              type: 'category',
              label: 'Case Management',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/Case Management' }]
            },
            {
              type: 'category',
              label: 'Mitre Attack',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Monitoring/MITRE ATT&CK' }]
            },
          ]
        },

        {
          type: 'category',
          label: 'User Management and Access Control',
          items: [
            {
              type: 'category',
              label: 'Users and Roles',
              items: [
                {
                  type: 'category',
                  label: 'DNIF Entities',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Users-and-Roles/DNIF-Entities' }]
                },
                {
                  type: 'category',
                  label: 'Manage Organization and users',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Users-and-Roles/Manage Organization and users' }]
                },
              ]
            },
            {
              type: 'category',
              label: 'Authentication',
              items: [
                {
                  type: 'category',
                  label: 'LDAP Authentication',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Authentication/LDAP Authentication' }]
                },

                {
                  type: 'category',
                  label: 'Two-Factor Authentication',
                  items: [{ type: 'autogenerated', dirName: 'hyperscale/User-Management-and-Access-Control/Authentication/Two - Factor Authentication' }]
                },
              ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Operations',
          items: [

            {
              type: 'category',
              label: 'Managing Streams',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Managing Streams' }]
            },

            {
              type: 'category',
              label: 'Slow Queries',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Slow Queries' }]
            },
            {
              type: 'category',
              label: 'Manage Tokens',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Manage Token' }]
            },
            {
              type: 'category',
              label: 'Event Stores',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Event Stores' }]
            },
            {
              type: 'category',
              label: 'Change Task Timeouts',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Change Task Timeouts' }]
            },
            {
              type: 'category',
              label: 'Machine Learning',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Operations/Machine Learning' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Platform Services',
          items: [
            {
              type: 'doc',
              id: 'hyperscale/Platform-Services/automation',
              label: 'Automation',
            },
            {
              type: 'category',
              label: 'Supported Automation',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/Supported Automation' }]
            },
            {
              type: 'category',
              label: 'Supported Automation-SSH',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/Supported Automation-SSH' }]
            },
            {
              type: 'category',
              label: 'API',
              items: [{ type: 'autogenerated', dirName: 'hyperscale/Platform-Services/API' }]
            },
          ]
        },
        {
          type: 'category',
          label: 'Troubleshooting and Debugging',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Troubleshooting-and-Debugging' }]
        },
        {
          type: 'category',
          label: 'DNIF AI',
          items: [
            { type: 'doc', id: 'hyperscale/DNIF-AI/Getting-Started-with-DNIF-AI/getting-started-with-dnif-ai', label: 'Getting Started with DNIF AI' },

          ]
        },
        {
          type: 'category',
          label: 'License Management and Billing',
          items: [
            {
              type: 'doc',
              id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Calculating-overage/calculating-overage-2',
              label: 'Calculating Overage',
            },
            {
              type: 'doc',
              id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Pricing-to-billing-how-it-works/pricing-to-billing-how-it-works-3',
              label: 'Pricing to billing, how it works',
            },
            {
              type: 'doc',
              id: 'hyperscale/License-Management-and-Billing/License-Management-and-Billing/Term-Based-Software-Subscription/term-based-software-subscription',
              label: 'Term Based Software Subscription',
            },
          ]
        },


        {
          type: 'category',
          label: 'DNIF Legal and Security Compliance',
          items: [
            {
              type: 'doc',
              id: 'hyperscale/DNIF-Legal-and-Security-Compliance/Data-Privacy-Policy/data-privacy-policy',
              label: 'Data Privacy Policy'
            },

            {
              type: 'doc',
              id: 'hyperscale/DNIF-Legal-and-Security-Compliance/DNIF-End-user-License-Agreement/dnif-end-user-license-agreement',
              label: 'DNIF End user License Agreement '
            }

          ]
        },
        {
          type: 'category',
          label: 'Policies',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Policies' }]
        },
        {
          type: 'category',
          label: 'PICO',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/PICO' }]
        },
        {
          type: 'category',
          label: 'Security Bulletins',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Security-Bulletins' }]
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{ type: 'autogenerated', dirName: 'hyperscale/Best-Practices' }]
        },
      ]}






]}; // <-- This closes the module.exports object

